-- Databricks notebook source
use gold

-- COMMAND ----------

-- MAGIC %md
-- MAGIC # Table DateDim DDL 

-- COMMAND ----------

CREATE OR REPlACE TABLE gold.DateDim (
        DateSK  int , 
        DayDate  date , 
        DayDateName  string , 
        FullDateName  string , 
        IsWeekdayFlag  string , 
        IsWeekendFlag  string , 
        IsBankHolidayFlag  string , 
        IsBusinessDayFlag  string , 
        IsBankBusinessDayFlag  string , 
        IsCorporateHolidayFlag  string , 
        IsFederalHolidayFlag  string , 
        WeekOfYearNumber  int , 
        PreviousDayDateSK  int , 
        PreviousDayDate  date , 
        NextDayDateSK  int , 
        NextDayDate  date , 
        BusinessDayDate  date , 
        BusinessDayDateSK  int , 
        PreviousBusinessDayDateSK  int , 
        PreviousBusinessDayDate  date , 
        NextBusinessDayDateSK  int , 
        NextBusinessDayDate  date , 
        SameDayWeekAgoDateSK  int , 
        SameDayWeekAgoDate  date , 
        SameDayMonthAgoDateSK  int , 
        SameDayMonthAgoDate  date , 
        SameDayYearAgoDateSK  int , 
        SameDayYearAgoDate  date , 
        IsFirstDayOfSundayStartWeekFlag  string , 
        IsFirstDayOfMondayStartWeekFlag  string , 
        IsFirstDayOfMonthFlag  string , 
        IsFirstDayOfQuarterFlag  string , 
        IsFirstDayOfYearFlag  string , 
        IsLastDayOfSundayStartWeekFlag  string , 
        IsLastDayOfMondayStartWeekFlag  string , 
        IsLastDayOfMonthFlag  string , 
        IsLastDayOfQuarterFlag  string , 
        IsLastDayOfYearFlag  string , 
        WeekSundayStartBeginDateSK  int , 
        WeekSundayStartBeginDate  date , 
        WeekSundayStartEndDateSK  int , 
        WeekSundayStartEndDate  date , 
        WeekSundayStartRangeName  string , 
        WeekSundayStartAbbrvRangeName  string , 
        WeekMondayStartBeginDateSK  int , 
        WeekMondayStartBeginDate  date , 
        WeekMondayStartEndDateSK  int , 
        WeekMondayStartEndDate  date , 
        WeekMondayStartRangeName  string , 
        WeekMondayStartAbbrvRangeName  string , 
        MonthBeginDateSK  int , 
        MonthBeginDate  date , 
        MonthEndDateSK  int , 
        MonthEndDate  date , 
        QuarterBeginDateSK  int , 
        QuarterBeginDate  date , 
        QuarterEndDateSK  int , 
        QuarterEndDate  date , 
        YearBeginDateSK  int , 
        YearBeginDate  date , 
        YearEndDateSK  int , 
        YearEndDate  date , 
        DayOfSundayStartWeekNumber  string , 
        DayOfMondayStartWeekNumber  string , 
        DayOfMonthNumber  int , 
        DayOfYearNumber  int , 
        MonthNumber  int , 
        QuarterNumber  int , 
        YearNumber  int , 
        DayName  string , 
        DayAbbrvName  string , 
        MonthSK  int , 
        MonthName  string , 
        MonthAbbrvName  string , 
        MonthAndYearName  string , 
        YearAndMonthName  string , 
        YearAndMonthAbbrvName  string , 
        MonthAbbrvAndYearName  string , 
        MonthAbbrvAndYearAbbrvName  string , 
        YearAbbrvAndMonthAbbrvName  string , 
        QuarterSK  int , 
        QuarterName  string , 
        QuarterAbbrvName  string , 
        QuarterAndYearName  string , 
        YearAndQuarterName  string , 
        YearAndQuarterAbbrvName  string , 
        QuarterAbbrvAndYearName  string , 
        QuarterAbbrvAndYearAbbrvName  string , 
        YearAbbrvAndQuarterAbbrvName  string , 
        YearSK  int , 
        YearName  string , 
        YearAbbrvName  string , 
        DayInEpochQuantity  int , 
        WeekInEpochQuantity  int , 
        MonthInEpochQuantity  int , 
        QuarterInEpochQuantity  int , 
        YearInEpochQuantity  int , 
        IsCurrentRecordInd  int GENERATED ALWAYS AS (1)  , 
        IsSourceRecordDeletedInd  int GENERATED ALWAYS AS (0) , 
        RecordEffectiveDateTime  timestamp , 
        RecordExpirationDateTime  timestamp , 
        ETLInsertBatchID  string GENERATED ALWAYS AS ('-1') , 
        RecordInsertDateTime  timestamp , 
        RecordInsertUserName  string GENERATED ALWAYS AS (CAST('Azure_Dbrics_User' AS String)) , 
        ETLUpdateBatchID  string GENERATED ALWAYS AS ('-1') , 
        RecordUpdateDateTime  timestamp , 
        RecordUpdateUserName  string GENERATED ALWAYS AS (CAST('Azure_Dbrics_User' AS String)), 
        RecordCheckSumNumber  string 
        )
     

-- COMMAND ----------

Optimize gold.DateDim
