-- Databricks notebook source
use silver;

-- describe table bronze.rasf_quote

-- COMMAND ----------

-- MAGIC %md
-- MAGIC # Table RocketAutoSalesforceQuote DDL 

-- COMMAND ----------

CREATE OR REPlACE TABLE silver.RocketAutoSalesforceQuote (
Id string,
OwnerId string,
IsDeleted boolean,
Name string,
RecordTypeId string,
CreatedDate timestamp,
CreatedById string,
LastModifiedDate timestamp,
LastModifiedById string,
SystemModstamp timestamp,
LastViewedDate timestamp,
LastReferencedDate timestamp,
OpportunityId string,
Pricebook2Id string,
ContactId string,
QuoteNumber string,
IsSyncing boolean,
ShippingHandling decimal(38,18),
Tax decimal(38,18),
Status string,
ExpirationDate timestamp,
Description string,
Subtotal decimal(38,18),
TotalPrice decimal(38,18),
LineItemCount int,
BillingStreet string,
BillingCity string,
BillingState string,
BillingPostalCode string,
BillingCountry string,
BillingStateCode string,
BillingCountryCode string,
BillingLatitude decimal(38,18),
BillingLongitude decimal(38,18),
BillingGeocodeAccuracy string,
ShippingStreet string,
ShippingCity string,
ShippingState string,
ShippingPostalCode string,
ShippingCountry string,
ShippingStateCode string,
ShippingCountryCode string,
ShippingLatitude decimal(38,18),
ShippingLongitude decimal(38,18),
ShippingGeocodeAccuracy string,
QuoteToStreet string,
QuoteToCity string,
QuoteToState string,
QuoteToPostalCode string,
QuoteToCountry string,
QuoteToStateCode string,
QuoteToCountryCode string,
QuoteToLatitude decimal(38,18),
QuoteToLongitude decimal(38,18),
QuoteToGeocodeAccuracy string,
AdditionalStreet string,
AdditionalCity string,
AdditionalState string,
AdditionalPostalCode string,
AdditionalCountry string,
AdditionalStateCode string,
AdditionalCountryCode string,
AdditionalLatitude decimal(38,18),
AdditionalLongitude decimal(38,18),
AdditionalGeocodeAccuracy string,
BillingName string,
ShippingName string,
QuoteToName string,
AdditionalName string,
Email string,
Phone string,
Fax string,
ContractId string,
AccountId string,
Discount decimal(38,18),
GrandTotal decimal(38,18),
CanCreateQuoteLineItems boolean,
APR__c decimal(38,18),
Amount_Financed__c decimal(38,18),
Emails_for_Invoice_Delivery__c string,
Payment_Terms__c string,
Application_Id__c string,
Appraisal__c string,
AutoFI__c string,
Customer_Url_Link__c string,
Customer_Url__c string,
Deal_Estimate__c decimal(38,18),
Deal_Expiry_Date__c string,
Down_Payment__c decimal(38,18),
Finance_Charge__c decimal(38,18),
Is_AutoFi_Deal_update__c boolean,
Monthly_Payment__c decimal(38,18),
Number_Of_Payments__c decimal(38,18),
Protection_Plans_SubTotal__c decimal(38,18),
TaxesAndFees_Sub_Total__c decimal(38,18),
Term_Months__c decimal(38,18),
Total_Of_Payments__c decimal(38,18),
Vehicle_Price__c decimal(38,18),
Vehicle__c string,
Backend_Pricing__c decimal(38,18),
Backend_Product__c string,
Lender__c string,
RecordChecksumNumber string ,
ETLInsertBatchID string GENERATED ALWAYS AS ('-1') ,
RecordInsertDateTime timestamp ,
RecordInsertUserName string GENERATED ALWAYS AS (CAST('Azure_Dbrics_User' AS String)) ,
ETLUpdateBatchID string GENERATED ALWAYS AS ('-1') ,
RecordUpdateDateTime timestamp  ,
RecordUpdateUserName string GENERATED ALWAYS AS (CAST('Azure_Dbrics_User' AS String))  
);
     

-- COMMAND ----------


