-- Databricks notebook source
use silver;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC # Table RocketAutoSalesforceuser DDL 

-- COMMAND ----------

CREATE OR REPlACE TABLE silver.RocketAutoSalesforceUser (
Id        string ,
Username        string ,
LastName        string ,
FirstName        string ,
MiddleName        string ,
Suffix        string ,
Name        string ,
CompanyName        string ,
Division        string ,
Department        string ,
Title        string ,
Street        string ,
City        string ,
State        string ,
PostalCode        string ,
Country        string ,
StateCode        string ,
CountryCode        string ,
Latitude        decimal(38,18) ,
Longitude        decimal(38,18) ,
GeocodeAccuracy        string ,
Email        string ,
EmailPreferencesAutoBcc        boolean ,
EmailPreferencesAutoBccStayInTouch        boolean ,
EmailPreferencesStayInTouchReminder        boolean ,
SenderEmail        string ,
SenderName        string ,
Signature        string ,
StayInTouchSubject        string ,
StayInTouchSignature        string ,
StayInTouchNote        string ,
Phone        string ,
Fax        string ,
MobilePhone        string ,
Alias        string ,
CommunityNickname        string ,
BadgeText        string ,
IsActive        boolean ,
TimeZoneSidKey        string ,
UserRoleId        string ,
LocaleSidKey        string ,
ReceivesInfoEmails        boolean ,
ReceivesAdminInfoEmails        boolean ,
EmailEncodingKey        string ,
ProfileId        string ,
UserType        string ,
LanguageLocaleKey        string ,
EmployeeNumber        string ,
DelegatedApproverId        string ,
ManagerId        string ,
LastLoginDate        timestamp ,
LastPasswordChangeDate        timestamp ,
CreatedDate        timestamp ,
CreatedById        string ,
LastModifiedDate        timestamp ,
LastModifiedById        string ,
SystemModstamp        timestamp ,
NumberOfFailedLogins        int ,
OfflineTrialExpirationDate        timestamp ,
OfflinePdaTrialExpirationDate        timestamp ,
UserPermissionsMarketingUser        boolean ,
UserPermissionsOfflineUser        boolean ,
UserPermissionsAvantgoUser        boolean ,
UserPermissionsCallCenterAutoLogin        boolean ,
UserPermissionsSFContentUser        boolean ,
UserPermissionsKnowledgeUser        boolean ,
UserPermissionsInteractionUser        boolean ,
UserPermissionsSupportUser        boolean ,
ForecastEnabled        boolean ,
UserPreferencesActivityRemindersPopup        boolean ,
UserPreferencesEventRemindersCheckboxDefault        boolean ,
UserPreferencesTaskRemindersCheckboxDefault        boolean ,
UserPreferencesReminderSoundOff        boolean ,
UserPreferencesDisableAllFeedsEmail        boolean ,
UserPreferencesDisableFollowersEmail        boolean ,
UserPreferencesDisableProfilePostEmail        boolean ,
UserPreferencesDisableChangeCommentEmail        boolean ,
UserPreferencesDisableLaterCommentEmail        boolean ,
UserPreferencesDisProfPostCommentEmail        boolean ,
UserPreferencesApexPagesDeveloperMode        boolean ,
UserPreferencesReceiveNoNotificationsAsApprover        boolean ,
UserPreferencesReceiveNotificationsAsDelegatedApprover        boolean ,
UserPreferencesHideCSNGetChatterMobileTask        boolean ,
UserPreferencesDisableMentionsPostEmail        boolean ,
UserPreferencesDisMentionsCommentEmail        boolean ,
UserPreferencesHideCSNDesktopTask        boolean ,
UserPreferencesHideChatterOnboardingSplash        boolean ,
UserPreferencesHideSecondChatterOnboardingSplash        boolean ,
UserPreferencesDisCommentAfterLikeEmail        boolean ,
UserPreferencesDisableLikeEmail        boolean ,
UserPreferencesSortFeedByComment        boolean ,
UserPreferencesDisableMessageEmail        boolean ,
UserPreferencesDisableBookmarkEmail        boolean ,
UserPreferencesDisableSharePostEmail        boolean ,
UserPreferencesEnableAutoSubForFeeds        boolean ,
UserPreferencesDisableFileShareNotificationsForApi        boolean ,
UserPreferencesShowTitleToExternalUsers        boolean ,
UserPreferencesShowManagerToExternalUsers        boolean ,
UserPreferencesShowEmailToExternalUsers        boolean ,
UserPreferencesShowWorkPhoneToExternalUsers        boolean ,
UserPreferencesShowMobilePhoneToExternalUsers        boolean ,
UserPreferencesShowFaxToExternalUsers        boolean ,
UserPreferencesShowStreetAddressToExternalUsers        boolean ,
UserPreferencesShowCityToExternalUsers        boolean ,
UserPreferencesShowStateToExternalUsers        boolean ,
UserPreferencesShowPostalCodeToExternalUsers        boolean ,
UserPreferencesShowCountryToExternalUsers        boolean ,
UserPreferencesShowProfilePicToGuestUsers        boolean ,
UserPreferencesShowTitleToGuestUsers        boolean ,
UserPreferencesShowCityToGuestUsers        boolean ,
UserPreferencesShowStateToGuestUsers        boolean ,
UserPreferencesShowPostalCodeToGuestUsers        boolean ,
UserPreferencesShowCountryToGuestUsers        boolean ,
UserPreferencesShowForecastingChangeSignals        boolean ,
UserPreferencesHideS1BrowserUI        boolean ,
UserPreferencesDisableEndorsementEmail        boolean ,
UserPreferencesPathAssistantCollapsed        boolean ,
UserPreferencesCacheDiagnostics        boolean ,
UserPreferencesShowEmailToGuestUsers        boolean ,
UserPreferencesShowManagerToGuestUsers        boolean ,
UserPreferencesShowWorkPhoneToGuestUsers        boolean ,
UserPreferencesShowMobilePhoneToGuestUsers        boolean ,
UserPreferencesShowFaxToGuestUsers        boolean ,
UserPreferencesShowStreetAddressToGuestUsers        boolean ,
UserPreferencesLightningExperiencePreferred        boolean ,
UserPreferencesPreviewLightning        boolean ,
UserPreferencesHideEndUserOnboardingAssistantModal        boolean ,
UserPreferencesHideLightningMigrationModal        boolean ,
UserPreferencesHideSfxWelcomeMat        boolean ,
UserPreferencesHideBiggerPhotoCallout        boolean ,
UserPreferencesGlobalNavBarWTShown        boolean ,
UserPreferencesGlobalNavGridMenuWTShown        boolean ,
UserPreferencesCreateLEXAppsWTShown        boolean ,
UserPreferencesFavoritesWTShown        boolean ,
UserPreferencesRecordHomeSectionCollapseWTShown        boolean ,
UserPreferencesRecordHomeReservedWTShown        boolean ,
UserPreferencesFavoritesShowTopFavorites        boolean ,
UserPreferencesExcludeMailAppAttachments        boolean ,
UserPreferencesSuppressTaskSFXReminders        boolean ,
UserPreferencesSuppressEventSFXReminders        boolean ,
UserPreferencesPreviewCustomTheme        boolean ,
UserPreferencesHasCelebrationBadge        boolean ,
UserPreferencesUserDebugModePref        boolean ,
UserPreferencesSRHOverrideActivities        boolean ,
UserPreferencesNewLightningReportRunPageEnabled        boolean ,
UserPreferencesReverseOpenActivitiesView        boolean ,
UserPreferencesHasSentWarningEmail        boolean ,
UserPreferencesHasSentWarningEmail238        boolean ,
UserPreferencesHasSentWarningEmail240        boolean ,
UserPreferencesHideBrowseProductRedirectConfirmation        boolean ,
UserPreferencesHideOnlineSalesAppWelcomeMat        boolean ,
ContactId        string ,
AccountId        string ,
CallCenterId        string ,
Extension        string ,
PortalRole        string ,
IsPortalEnabled        boolean ,
FederationIdentifier        string ,
AboutMe        string ,
FullPhotoUrl        string ,
SmallPhotoUrl        string ,
IsExtIndicatorVisible        boolean ,
OutOfOfficeMessage        string ,
MediumPhotoUrl        string ,
DigestFrequency        string ,
DefaultGroupNotificationFrequency        string ,
LastViewedDate        timestamp ,
LastReferencedDate        timestamp ,
BannerPhotoUrl        string ,
SmallBannerPhotoUrl        string ,
MediumBannerPhotoUrl        string ,
IsProfilePhotoActive        boolean ,
Five9__Five9AgentId__c        string ,
Five9__Five9Agent_Login_TimeStamp__c        string ,
amazonconnect__Amazon_Connect_Username__c        string ,
RecordChecksumNumber string ,
ETLInsertBatchID string GENERATED ALWAYS AS ('-1') ,
RecordInsertDateTime timestamp ,
RecordInsertUserName string GENERATED ALWAYS AS (CAST('Azure_Dbrics_User' AS String)) ,
ETLUpdateBatchID string GENERATED ALWAYS AS ('-1') ,
RecordUpdateDateTime timestamp  ,
RecordUpdateUserName string GENERATED ALWAYS AS (CAST('Azure_Dbrics_User' AS String))  
);
     

-- COMMAND ----------

-- MAGIC %md
-- MAGIC # Add Columns DDL

-- COMMAND ----------


--Alter table Silver.RocketAutoSalesforceuser
--Add columns 
--(test string) 
