-- Databricks notebook source
Use Silver;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC # Table RocketAutoSalesforceAccount DDL 

-- COMMAND ----------

CREATE OR REPlACE TABLE Silver.RocketAutoSalesforceAccount (
Id        string ,
AccountNumber        string ,
AccountSource        string ,
Account_Id__c        string ,
Account_Record_ID__c        string ,
Active_Five9_List_Item__c        string ,
Active_Five9_List__c        string ,
Active_Opportunity_Create_DateTime__c        timestamp ,
Active_Opportunity_Stage__c        string ,
Active_Opportunity__c        string ,
Active__c        boolean ,
Active__pc        boolean ,
Added_to_Five9__c        boolean ,
AnnualRevenue        decimal(38,18) ,
Appointment_Confirmed__c        boolean ,
AutoFi_Dealer_ID__c        string ,
BillingCity        string ,
BillingCountry        string ,
BillingCountryCode        string ,
BillingGeocodeAccuracy        string ,
BillingLatitude        decimal(38,18) ,
BillingLongitude        decimal(38,18) ,
BillingPostalCode        string ,
BillingState        string ,
BillingStateCode        string ,
BillingStreet        string ,
Billing_Latitude__c        decimal(38,18) ,
Billing_Longitude__c        decimal(38,18) ,
Call_Campaign_Expiration_Date__c        timestamp ,
Campaign_Expiration_Date__c        timestamp ,
ChannelProgramLevelName        string ,
ChannelProgramName        string ,
Closing_Date__c        timestamp ,
CreatedById        string ,
CreatedDate        timestamp ,
CTIA_Consent__c        boolean ,
Dealer__pc        string ,
Description        string ,
Email_Sales__c        string ,
et4ae5__HasOptedOutOfMobile__pc        boolean ,
et4ae5__Mobile_Country_Code__pc        string ,
Fax        string ,
FirstName        string ,
Five9_Call_ASAP__c        boolean ,
Industry        string ,
Inventory_Live_Date__c        timestamp ,
Inventory_Live__c        string ,
Inventory_Provider_Dealer_Id__c        string ,
Inventory_Provider_Dealer_Name__c        string ,
IsDeleted        boolean ,
IsPartner        boolean ,
IsPersonAccount        boolean ,
Jigsaw        string ,
JigsawCompanyId        string ,
LastActivityDate        timestamp ,
LastModifiedById        string ,
LastModifiedDate        timestamp ,
LastName        string ,
LastReferencedDate        timestamp ,
LastViewedDate        timestamp ,
Lead_Collection_Method__c        string ,
Lead_Routing_Method__c        string ,
Loan_Number__c        string ,
Logo_URL__c        string ,
MasterRecordId        string ,
MiddleName        string ,
MSA_ID__c        string ,
MSA_Name__c        string ,
Name        string ,
National__c        string ,
NumberOfEmployees        int ,
Number_of_Roof_Tops__c        string ,
OwnerId        string ,
Ownership        string ,
ParentId        string ,
PEID__c        string ,
PersonContactId        string ,
PersonDepartment        string ,
PersonEmail        string ,
PersonEmailBouncedDate        timestamp ,
PersonEmailBouncedReason        string ,
PersonHasOptedOutOfEmail        boolean ,
PersonLastCURequestDate        timestamp ,
PersonLastCUUpdateDate        timestamp ,
PersonMailingCity        string ,
PersonMailingCountry        string ,
PersonMailingCountryCode        string ,
PersonMailingGeocodeAccuracy        string ,
PersonMailingLatitude        decimal(38,18) ,
PersonMailingLongitude        decimal(38,18) ,
PersonMailingPostalCode        string ,
PersonMailingState        string ,
PersonMailingStateCode        string ,
PersonMailingStreet        string ,
PersonMobilePhone        string ,
PersonTitle        string ,
Phone        string ,
Phone_Sales__c        string ,
Phone_Service__c        string ,
PhotoUrl        string ,
Rating        string ,
RecordTypeId        string ,
RecordTypeName__c        string ,
Rocket_Auto_Client_Id__c        string ,
Rocket_Auto_Dealer_Code__c        string ,
Sales_Hours__c        string ,
Salutation        string ,
Scheduled_Appointment__c        timestamp ,
Send_to_Five9__c        boolean ,
ShippingCity        string ,
ShippingCountry        string ,
ShippingCountryCode        string ,
ShippingGeocodeAccuracy        string ,
ShippingLatitude        decimal(38,18) ,
ShippingLongitude        decimal(38,18) ,
ShippingPostalCode        string ,
ShippingState        string ,
ShippingStateCode        string ,
ShippingStreet        string ,
Sic        string ,
SicDesc        string ,
Site        string ,
Suffix        string ,
SystemModstamp        timestamp ,
TickerSymbol        string ,
Title__pc        string ,
Type        string ,
UserID__c        string ,
Vehicle_Price__c        decimal(38,18) ,
Website        string ,
RecordChecksumNumber string,
ETLInsertBatchID string GENERATED ALWAYS AS ('-1') ,
RecordInsertDateTime timestamp ,
RecordInsertUserName string GENERATED ALWAYS AS (CAST('Azure_Dbrics_User' AS String)) ,
ETLUpdateBatchID string GENERATED ALWAYS AS ('-1') ,
RecordUpdateDateTime timestamp  ,
RecordUpdateUserName string GENERATED ALWAYS AS (CAST('Azure_Dbrics_User' AS String)) 
 );


-- COMMAND ----------

-- MAGIC %md
-- MAGIC # Add Columns DDL

-- COMMAND ----------

--Alter table Silver.RocketAutoSalesforceAccount
--Add columns 
--(test string) 

